FROM continuumio/miniconda3

COPY environment.yml /

RUN conda env create -f /environment.yml && \
    conda clean -afy

ENV PATH /opt/conda/envs/myenv/bin:$PATH

COPY . .

CMD ["streamlit", "run", "main.py"]
