version: "3.9"
services:
  bot:
    container_name: candles_downloader
    image: dardonacci/hummingbot:development
    volumes:
      - "../../data/candles:/home/hummingbot/data"
      - "../bot_configs/data_downloader:/home/hummingbot/conf"
      - "../bot_configs/data_downloader/connectors:/home/hummingbot/conf/connectors"
    environment:
      - CONFIG_PASSWORD=a
      - CONFIG_FILE_NAME=download_candles.py
    env_file:
      - ../scripts_configs/data_downloader_config.yml
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: 5
    tty: true
    stdin_open: true
    network_mode: host
